TWEAK_NAME = Liddell
Liddell_FILES = Liddell.m MarqueeLabel.swift
Liddell_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN
Liddell_FRAMEWORKS = UIKit
Liddell_EXTRA_FRAMEWORKS = Cephei
Liddell_LIBRARIES = kitten gcuniversal

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/tweak.mk
