BUNDLE_NAME = LiddellPreferences
LiddellPreferences_FILES = $(wildcard Controllers/*.m Cells/*.m)
LiddellPreferences_FRAMEWORKS = UIKit
LiddellPreferences_PRIVATE_FRAMEWORKS = Preferences
LiddellPreferences_LIBRARIES = gcuniversal
LiddellPreferences_INSTALL_PATH = /Library/PreferenceBundles
LiddellPreferences_CFLAGS = -fobjc-arc -DTHEOS_LEAN_AND_MEAN

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
